-- ============================================================================
-- Health at Home · Clínica Santa Bárbara
-- Fase 0 — Cimientos: sedes, perfiles, RBAC, multi-sede, RLS y auditoría
-- Zona horaria de referencia: America/Bogota (se almacena en UTC / timestamptz)
-- ============================================================================

-- ------------------------------------------------------------------ Extensiones
create extension if not exists "pgcrypto";

-- ------------------------------------------------------------------ Sedes
create table if not exists public.sedes (
  id         uuid primary key default gen_random_uuid(),
  codigo     text unique not null,
  nombre     text not null,
  ciudad     text,
  direccion  text,
  telefonos  text,
  activo     boolean not null default true,
  creado_en  timestamptz not null default now()
);

-- ------------------------------------------------------------------ Perfiles (1:1 con auth.users)
create table if not exists public.perfiles (
  id                       uuid primary key references auth.users (id) on delete cascade,
  nombres                  text,
  apellidos                text,
  cedula                   text,
  especialidad             text,
  registro_medico          text,
  color_agenda             text,
  debe_cambiar_contrasena  boolean not null default true,
  activo                   boolean not null default true,
  creado_en                timestamptz not null default now(),
  actualizado_en           timestamptz not null default now()
);

-- ------------------------------------------------------------------ RBAC: roles y permisos
create table if not exists public.roles (
  id          uuid primary key default gen_random_uuid(),
  nombre      text unique not null,
  descripcion text,
  creado_en   timestamptz not null default now()
);

create table if not exists public.permisos (
  id          uuid primary key default gen_random_uuid(),
  modulo      text not null,
  accion      text not null,             -- ver | crear | editar | anular | exportar
  descripcion text,
  unique (modulo, accion)
);

create table if not exists public.rol_permisos (
  rol_id     uuid not null references public.roles (id) on delete cascade,
  permiso_id uuid not null references public.permisos (id) on delete cascade,
  primary key (rol_id, permiso_id)
);

-- Asignación de roles a usuarios (opcionalmente acotada a una sede)
create table if not exists public.usuario_roles (
  usuario_id uuid not null references public.perfiles (id) on delete cascade,
  rol_id     uuid not null references public.roles (id) on delete cascade,
  sede_id    uuid references public.sedes (id) on delete cascade,
  primary key (usuario_id, rol_id)
);

-- Alcance multi-sede del usuario
create table if not exists public.usuario_sedes (
  usuario_id uuid not null references public.perfiles (id) on delete cascade,
  sede_id    uuid not null references public.sedes (id) on delete cascade,
  primary key (usuario_id, sede_id)
);

-- ------------------------------------------------------------------ Auditoría (inmutable)
create table if not exists public.audit_log (
  id            bigint generated by default as identity primary key,
  usuario_id    uuid,
  accion        text not null,           -- INSERT | UPDATE | DELETE | READ
  entidad       text not null,
  registro_id   text,
  datos_antes   jsonb,
  datos_despues jsonb,
  ip            inet,
  ocurrido_en   timestamptz not null default now()
);

-- ============================================================================
-- Funciones auxiliares de seguridad
-- ============================================================================

-- ¿El usuario actual tiene el rol indicado?
create or replace function public.tiene_rol(p_rol text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1
    from public.usuario_roles ur
    join public.roles r on r.id = ur.rol_id
    where ur.usuario_id = auth.uid() and r.nombre = p_rol
  );
$$;

-- ¿Es administrador?
create or replace function public.es_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select public.tiene_rol('Administrador');
$$;

-- Sedes a las que el usuario actual tiene acceso
create or replace function public.mis_sedes()
returns setof uuid
language sql stable security definer set search_path = public
as $$
  select sede_id from public.usuario_sedes where usuario_id = auth.uid();
$$;

-- ============================================================================
-- Trigger: al crear un usuario en auth.users, crear su perfil
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.perfiles (id, nombres, apellidos, debe_cambiar_contrasena)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nombres', ''),
    coalesce(new.raw_user_meta_data ->> 'apellidos', ''),
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- Trigger genérico de auditoría
-- ============================================================================
create or replace function public.fn_auditoria()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  v_id text;
begin
  v_id := coalesce((to_jsonb(new) ->> 'id'), (to_jsonb(old) ->> 'id'));
  insert into public.audit_log (usuario_id, accion, entidad, registro_id, datos_antes, datos_despues)
  values (
    auth.uid(),
    tg_op,
    tg_table_name,
    v_id,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end
  );
  return coalesce(new, old);
end;
$$;

-- Auditar cambios sobre perfiles y asignaciones sensibles
drop trigger if exists aud_perfiles on public.perfiles;
create trigger aud_perfiles after insert or update or delete on public.perfiles
  for each row execute function public.fn_auditoria();

drop trigger if exists aud_usuario_roles on public.usuario_roles;
create trigger aud_usuario_roles after insert or update or delete on public.usuario_roles
  for each row execute function public.fn_auditoria();

-- ============================================================================
-- Row Level Security
-- ============================================================================
alter table public.sedes          enable row level security;
alter table public.perfiles        enable row level security;
alter table public.roles           enable row level security;
alter table public.permisos        enable row level security;
alter table public.rol_permisos    enable row level security;
alter table public.usuario_roles   enable row level security;
alter table public.usuario_sedes   enable row level security;
alter table public.audit_log       enable row level security;

-- Sedes: el usuario ve sus sedes; el admin, todas
drop policy if exists sedes_select on public.sedes;
create policy sedes_select on public.sedes for select
  using (public.es_admin() or id in (select public.mis_sedes()));

drop policy if exists sedes_admin_todo on public.sedes;
create policy sedes_admin_todo on public.sedes for all
  using (public.es_admin()) with check (public.es_admin());

-- Perfiles: cada quien ve/edita el suyo; el admin, todos
drop policy if exists perfiles_propio_select on public.perfiles;
create policy perfiles_propio_select on public.perfiles for select
  using (id = auth.uid() or public.es_admin());

drop policy if exists perfiles_propio_update on public.perfiles;
create policy perfiles_propio_update on public.perfiles for update
  using (id = auth.uid() or public.es_admin())
  with check (id = auth.uid() or public.es_admin());

drop policy if exists perfiles_admin_todo on public.perfiles;
create policy perfiles_admin_todo on public.perfiles for all
  using (public.es_admin()) with check (public.es_admin());

-- Catálogos de RBAC: lectura para autenticados, escritura solo admin
drop policy if exists roles_lectura on public.roles;
create policy roles_lectura on public.roles for select using (auth.uid() is not null);
drop policy if exists roles_admin on public.roles;
create policy roles_admin on public.roles for all using (public.es_admin()) with check (public.es_admin());

drop policy if exists permisos_lectura on public.permisos;
create policy permisos_lectura on public.permisos for select using (auth.uid() is not null);
drop policy if exists permisos_admin on public.permisos;
create policy permisos_admin on public.permisos for all using (public.es_admin()) with check (public.es_admin());

drop policy if exists rolperm_lectura on public.rol_permisos;
create policy rolperm_lectura on public.rol_permisos for select using (auth.uid() is not null);
drop policy if exists rolperm_admin on public.rol_permisos;
create policy rolperm_admin on public.rol_permisos for all using (public.es_admin()) with check (public.es_admin());

-- Asignaciones: el usuario ve las suyas; el admin gestiona todas
drop policy if exists usuroles_select on public.usuario_roles;
create policy usuroles_select on public.usuario_roles for select
  using (usuario_id = auth.uid() or public.es_admin());
drop policy if exists usuroles_admin on public.usuario_roles;
create policy usuroles_admin on public.usuario_roles for all
  using (public.es_admin()) with check (public.es_admin());

drop policy if exists ususedes_select on public.usuario_sedes;
create policy ususedes_select on public.usuario_sedes for select
  using (usuario_id = auth.uid() or public.es_admin());
drop policy if exists ususedes_admin on public.usuario_sedes;
create policy ususedes_admin on public.usuario_sedes for all
  using (public.es_admin()) with check (public.es_admin());

-- Auditoría: solo lectura para admin; inserción vía triggers (security definer). Nadie actualiza/borra.
drop policy if exists audit_admin_select on public.audit_log;
create policy audit_admin_select on public.audit_log for select using (public.es_admin());
